// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpjtinbpcpqaizpxlfru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwanRpbmJwY3BxYWl6cHhsZnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3ODMzMjEsImV4cCI6MjA3NzM1OTMyMX0.UK-WWizUUnOCL8ZdhonOy2C4lYN-T8m01doufWIbbxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});